name = "cuckoo-catalog"
type = "javascript"
account_id = ""
workers_dev = true
observability = { enabled = true }

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker"

[env.production]
name = "cuckoo-catalog-prod"
